repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        name: pip-compile
        args: [--output-file=requirements.txt]
        files: ^pyproject.toml$
      - id: pip-compile
        name: pip-compile-dev
        args: [--extra=dev, --output-file=requirements-dev.txt]
        files: ^pyproject.toml$
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        name: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
