alarms:
  invalid_input: true
  warning_in_operator_logs: false
checkers:
  state:
    analysis:
      dependency: false
      taint: false
    enable_canonicalization: true
    enable_default_value_comparison: true
  custom:
    - name: foo
io:
  write_result_each_generation: true
mode: 'whitebox'
strict: true
notifications:
  enabled: false
ray:
  enabled: false
