alarms:
  warning_in_operator_logs: false
checkers:
  state:
    enable_canonicalization: true
  custom:
    - name: foo
mode: 'whitebox'
strict: true
notifications:
  enabled: false
parallel:
  executor: 'process'
