apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: test-cluster
spec:
  configUpdateStrategy: RollingUpdate
  enableDynamicConfiguration: true
  helper:
    image: busybox:1.34.1
  pd:
    baseImage: pingcap/pd
    config: "[dashboard]\n  internal-proxy = true\n"
    maxFailoverCount: 0
    mountClusterClientSecret: true
    replicas: 3
    requests:
      storage: 10Gi
  pvReclaimPolicy: Retain
  tidb:
    baseImage: pingcap/tidb
    config: "[performance]\n  tcp-keep-alive = true\n"
    maxFailoverCount: 0
    podManagementPolicy: ''
    replicas: 3
    service:
      externalTrafficPolicy: Local
      type: NodePort
    storageVolumes:
    - mountPath: ACTOKEY
      name: ACTOKEY
      storageClassName: standard
      storageSize: ACTOKEY
    - mountPath: ACTOKEY
      name: ACTOKEY
      storageClassName: standard
      storageSize: ACTOKEY
    - mountPath: ACTOKEY
      name: ACTOKEY
      storageClassName: standard
      storageSize: ACTOKEY
    - mountPath: null
      name: ACTOKEY
      storageClassName: standard
      storageSize: ACTOKEY
  tikv:
    baseImage: pingcap/tikv
    config: 'log-level = "info"

      '
    maxFailoverCount: 0
    mountClusterClientSecret: true
    recoverFailover: false
    replicas: 3
    requests:
      storage: 100Gi
    separateRaftLog: true
  timezone: UTC
  version: v5.4.0
