apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: test-cluster
spec:
  redis:
    customConfig:
    - maxclients 100
    - hz 50
    - timeout 60
    - tcp-keepalive 60
    - client-output-buffer-limit normal 0 0 0
    - client-output-buffer-limit slave 1000000000 1000000000 0
    - client-output-buffer-limit pubsub 33554432 8388608 60
    exporter:
      enabled: true
    imagePullPolicy: IfNotPresent
    replicas: 3
    tolerations:
    - effect: NoSchedule
      key: test-key
      operator: Equal
      value: test-value
  sentinel:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: security
                operator: In
                values:
                - us-west-1
            topologyKey: failure-domain.beta.kubernetes.io/zone
          weight: 95
    customConfig:
    - down-after-milliseconds 2000
    - failover-timeout 3000
    imagePullPolicy: IfNotPresent
    replicas: 3
