---
- name: Install Docker
  hosts: all
  become: true
  roles:
    - geerlingguy.docker

  tasks:
    - name: Create docker group
      ansible.builtin.group:
        name: "docker"
        state: present

    - name: Adding user {{ user.stdout }} to docker group
      ansible.builtin.user:
        name: "{{ ansible_user | default(lookup('env', 'USER')) }}"
        groups: "docker"
        append: "yes"