---
- name: Install kubectl
  hosts: all
  become: true

  tasks:
    - name: download kubectl
      shell: curl -LO https://dl.k8s.io/release/v1.22.9/bin/linux/amd64/kubectl
    
    - name: install kubectl
      shell: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl