---
- name: Install python packages
  hosts: all
  become: true
  vars_files:
    - data.yaml
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Add python repository
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        filename: "python"
        update_cache: yes

    - name: Install python3
      apt:
        name: python3.10
        state: present
        update_cache: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install python3 venv
      apt:
        name: python3.10-venv
        state: present
        update_cache: yes

    - name: Get the home directory
      become: false
      command: echo $HOME
      register: home

    - name: Install python packages using pip
      pip:
        # Implication: this script should happen after acto.yml
        requirements: "{{ home.stdout }}/workdir/acto/requirements.txt"
        state: present
        virtualenv: "{{ home.stdout }}/workdir/acto/venv"
        virtualenv_command: python3.10 -m venv
