---
- name: Start Ray Head
  hosts: all[0]
  vars:
    user_home: "{{ ansible_env.HOME }}"
  tasks:
  - name: Create head service
    become: true
    ansible.builtin.template:
      src: ray-head.service
      dest: /lib/systemd/system/ray.service
      mode: 644
    notify:
    - Restart ray

  - name: Start ray head
    ansible.builtin.service:
      name: ray
      state: started

  handlers:
    - name: Restart ray
      ansible.builtin.systemd:
        daemon_reload: true
        name: ray
        state: restarted