name: All Bug Reproduction
on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at 00:00 UTC
  workflow_dispatch:
jobs:
  bug_reproduction:
    timeout-minutes: 1440
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          make
      - name: Create profile dir with 777 mode
        run: |
          mkdir -m 777 -p profile/data
      - name: Run bug reproduction
        run: |
          python -m pytest test/e2e_tests -m "all_bug_reproduction" -s
