name: Kubernetes Engine Test
on: 
  push:
    path: 
      - acto/kubernetes_engine/**
jobs:
  KubernetesEngineTest:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          make
      - name: Install Kind
        run: |
          go install sigs.k8s.io/kind@v0.20.0
      - name: Install minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
      - name: Run KubernetesEngineTest
        run: |
          pytest -m "kubernetes_engine"